const businessesTypes = {
    FETCH_BUSINESSES: "FETCH_BUSINESSES",
    ADD_BUSINESS: "ADD_BUSINESS",
    DELETE_BUSINESS: "DELETE_BUSINESS",
    CHANGE_BUSINESS_CATEGORY: 'CHANGE_BUSINESS_CATEGORY'
}

export default businessesTypes;